// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7PaIq3v5MpCjQgVCCaJGGl648AG8kF1c',
    appId: '1:272841331889:web:0324aa004bed91377bbe90',
    messagingSenderId: '272841331889',
    projectId: 'dhwanisetu',
    authDomain: 'dhwanisetu.firebaseapp.com',
    storageBucket: 'dhwanisetu.firebasestorage.app',
    measurementId: 'G-E9858165MM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2A2D3c-XQVj6mE-hRE7vBicNH-QAfVDg',
    appId: '1:272841331889:android:3dab7a9cec275c467bbe90',
    messagingSenderId: '272841331889',
    projectId: 'dhwanisetu',
    storageBucket: 'dhwanisetu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCID3xqJNH3iCUDt1wbn-dcYsB1soqiR60',
    appId: '1:272841331889:ios:4d43dd3b02beaade7bbe90',
    messagingSenderId: '272841331889',
    projectId: 'dhwanisetu',
    storageBucket: 'dhwanisetu.firebasestorage.app',
    iosBundleId: 'com.example.dhwanisetu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCID3xqJNH3iCUDt1wbn-dcYsB1soqiR60',
    appId: '1:272841331889:ios:4d43dd3b02beaade7bbe90',
    messagingSenderId: '272841331889',
    projectId: 'dhwanisetu',
    storageBucket: 'dhwanisetu.firebasestorage.app',
    iosBundleId: 'com.example.dhwanisetu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7PaIq3v5MpCjQgVCCaJGGl648AG8kF1c',
    appId: '1:272841331889:web:7080abdd2b0ae9b37bbe90',
    messagingSenderId: '272841331889',
    projectId: 'dhwanisetu',
    authDomain: 'dhwanisetu.firebaseapp.com',
    storageBucket: 'dhwanisetu.firebasestorage.app',
    measurementId: 'G-N8SQGGTBK9',
  );
}
